# Generated by Django 5.0.6 on 2024-06-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='device_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tank',
            name='refresh_token',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Alipan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('refresh_token', models.TextField()),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.proxies', verbose_name='代理')),
            ],
            options={
                'verbose_name': '阿里云盘配置',
                'verbose_name_plural': '阿里云盘',
            },
        ),
    ]
